### ISSUE TITLE
Recategorization

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hyrule#1]
@scauligi @allison-casey - I'm not sure if you're watching this repository yet, and I want your eyeballs.

Hyrule and its companion branch of Hy basically work now, except for the documentation. One thing I want to clear up before I do that is how to categorize Hyrule's many bits. This isn't too important because the user will be able to import or require any name directly from `hyrule`, at the top level. Its chief significance will be in how things are presented in the documentation.

Here's my proposal of the new categories and what will go in them. `contrib` and `extra` will be gone. What do you think?

- `macrotools`: Tools for writing and handling macros
  - `defmacro!` `defmacro/g!` `with-gensyms` `macroexpand-all`
- `anaphoric`: Anaphoric macros
  - Members as in `hy.extra.anaphoric`
- `control`: Control structures
  - `defmain` `cfor` `list-n` `do-n` `unless` `lif` `loop`
- `argmove`: Macros for calls with unusual argument placement 
  -  `->` `->>` `as->` `doto`
- `collections`: Tools for iterables etc.
  -  `assoc` `butlast` `coll?` `distinct` `drop-last` `flatten` `rest` `ncut` `#:` `walk` `postwalk` `prewalk`
- `destructure`: Macros for destructing collections
  - Members as in `hy.contrib.destructure`
- `pprint`: Pretty-printing data structures
  - Members as in `hy.contrib.pprint`
- `sequences`: Lazy, indexable iterables
  - Members as in `hy.contrib.sequences`
- `let`: Classical Lisp scoping
  - `let` `smacrolet`
- `misc`: Everything else
  - `comment` `of` `constantly` `dec` `inc` `parse-args` `xor` `profile/calls` `profile/cpu`

**Comment by allison-casey** [comment]
is there any methods/macros in `argmove` that would prevent it from being called `threading`?

i would suggest breaking collections into `iterables` (or `sequences`) for iterable methods/macros and `collections` for `Mapping`'s. This is how both `toolz` and `funcy` separate their api and it works quite well in my experience. If you do that you can move all the `contrib.sequences` in there as well. I like everything else.

**Comment by Kodiologist** [comment]
> are there any methods/macros in `argmove` that would prevent it from being called `threading`?

Just those four, but "threading" is already used to mean something else in programming.

> i would suggest breaking collections into `iterables` (or `sequences`) for iterable methods/macros and `collections` for `Mapping`'s.

I think most of what's there works for both iterables and some non-iterables like mappings. So I guess most of them would stay there while `butlast`, `drop-last`, `distinct`, and `rest` would go to a new category `iterables` (avoiding the name "sequences" to avoid confusion with our `Sequence` type).

**Comment by Kodiologist** [comment]
Recategorization complete.
