### ISSUE TITLE
Internal functions and macros appear in the generated documentation

### ISSUE THREAD

**Issue by Kodiologist** [hylang/hyrule#10]
For example, the macro `rit` in `anaphoric`. https://github.com/hylang/sphinxcontrib-hydomain/issues/12 seems to be blocking.

**Comment by Kodiologist** [comment]
@allison-casey Can you figure this out? I'm hesitant to release Hyrule with this issue.

**Comment by allison-casey** [comment]
Let me take a look today

**Comment by allison-casey** [comment]
should be fixed now. if you want macros & and members to be documented you need both `:members:` and `:macros:`. To get specific macros you would add the name to `:macros:` not `:members:`. The fix i just pushed should respect all possible combinations of all macros but some members, some members but no macros, etc.

**Comment by Kodiologist** [comment]
Outstanding. Is `:tags:` no longer a thing, in favor of `:macros:`?

**Comment by allison-casey** [comment]
Yes it's gone

**Comment by allison-casey** [comment]
can this be closed now that my fix has been PR'd into master?

**Comment by Kodiologist** [comment]
No, I'm still working on getting the right items into the documentation. Setting `:members:` and `:macros:` seems to be working out all right for the most part, but `pprint` is tricky, and I think I accidentally junked all your tests for `pprint` when I moved stuff to Hyrule. Le sigh.

**Comment by allison-casey** [comment]
https://github.com/allison-casey/hy/blob/contrib/pprint/tests/native_tests/contrib/test_pprint.hy good thing i never delete my branches lol
