### ISSUE TITLE
`defmain` does not define a `main` function as documented

### ISSUE THREAD

**Issue by narpfel** [hylang/hyrule#22]
[The documentation](https://hyrule.readthedocs.io/en/master/#hyrule.control.defmain) states that `defmain` is equivalent to defining a `main` function in Python, but it actually uses [an anonymous function](https://github.com/hylang/hyrule/blob/86dfbdb6cb3fa06009bd492185e6785af66d2fcc/hyrule/control.hy#L117) inside the `if __name__ == "__main__"` block. This means that the `main` function is not callable (and not importable from other modules), which prevents useful things like unit testing the `main` function or calling it from the REPL.

Minimal example:
```hy
; foo.hy
(require hyrule [defmain])

(defmain [] (print "Hello world"))
```

Actual behaviour:
```pycon
>>> import hy
>>> import foo
>>> foo.main()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'foo' has no attribute 'main'
```

Expected behaviour:
```pycon
>>> import hy
>>> import foo
>>> foo.main()
Hello world
```

It seems the original (conforming to the documentation) behaviour was changed in hylang/hy#814 without updating the documentation.

**Comment by Kodiologist** [comment]
Good detective work. So, it seems that the advantage of actually creating a function named `main` is that you can call it elsewhere, whereas the advantage of creating an anonymous function is that you can use the name "main" for a subroutine thereof. Sounds like you'd prefer the former, right? It is a little counterintuitive that a form would define something named "main" without using the actual symbol `main` anywhere, though.

**Comment by narpfel** [comment]
I don’t have a preference as to whether `defmain` should declare `main` (though it would be convenient). Manually defining a `main` function and just calling that in `defmain` is an easy workaround.

I was just surprised that something the docs say should be possible wasn’t. Documenting that `defmain` generates an anonymous function would be fine for me.
