### ISSUE TITLE
importing hyrule

### ISSUE THREAD

**Issue by silver-dragon** [hylang/hyrule#59]
Hyrule docs say you can simply `(import hyrule)` however I have found that to be incorrect. 
After a long string of failed attempts I found that for macros you must specify the whole namespace and macro name like this:
```hy
(require hyrule.argmove [->])
(require hyrule.collections [assoc])
```
and for functions you have to import like this:
```hy
(import hyrule [pprint dec inc])
```

Can the documentation be updated accordingly?

### Discussed in https://github.com/hylang/hy/discussions/2301

<div type='discussions-op-text'>

<sup>Originally posted by **esakilpi** June  4, 2022</sup>
I have been trying to import collections.assoc from hyrule, but I always get the same error. Even with (import hyrule).
I guess there is a bug  in macrotools.macroexpansion-all that prevents the import?

This is the error message:
```
hy.errors.HyMacroExpansionError: 

  File ".../lib/python3.8/site-packages/hyrule/macrotools.hy", line 113
    (cond [(in (get form 0) '[unquote unquote-splice])
                      (+quote -1)]
                     [(= (get form 0) 'quasiquote) (+quote)]
                     [True (traverse form)])]
    ^^
expanding macro cond
  TypeError: `cond` needs an even number of arguments
```</div>

**Comment by silver-dragon** [comment]
What I was having trouble with was the differences in name spaces between the macro and the functions. 
There are detailed examples given so its only through trial and error that I found that functions don't need to have the name space like (import hyrule.hypprint [pprint])

**Comment by Kodiologist** [comment]
Notice the sentence "All of Hyrule's contents can be imported or required directly from the top-level module `hyrule`." That goes for both functions and macros, hence "imported or required".

**Comment by Kodiologist** [comment]
I don't get how you arrived at that conclusion. That's not what the sentence says, nor would it be consistent with how `import` works in general.
 
Overall, it looks to me like the documentation for both Hy and Hyrule is complete and correct with respect to the issues discussed here. There's even an example of importing and requiring stuff from Hyrule at the end of the Hy tutorial. Do you think anything specific needs to be added?
