### ISSUE TITLE
Infinite recursion when calling `len` or `list` on a finite `Sequence`

### ISSUE THREAD

**Issue by Jlobblet** [hylang/hyrule#63]
When trying to evaluate the length or collect a new (finite) `Sequence` into a list, infinite recursion resulting in a `RecursionError`.

Example code to reproduce:

```hy
(require hyrule [seq])
(import hyrule [end-sequence])
(list (seq [n] (if (< n 5) n (end-sequence))))
```

It may also be useful to set the maximum recursion depth to a lower value for debugging:

```hy
(import sys)
(sys.setrecursionlimit 100)
```

This error is caused as follows:

1. The new `Sequence` is created, and during `__init__` it sets `high-water` to `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L49
2. When calling `len` or `list` (which calls `__len__`), local variable `index` is set to `high-water` = `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L78
3. `__getitem__` is called with `n` = `-1`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L80
4. When `n` is negative, `__getitem__` calls `len`
  https://github.com/hylang/hyrule/blob/2219c0dd2034a38183c25109b4ae390140f39c67/hyrule/sequences.hy#L56-L59
5. Since `high-water` is still `-1`, step 2 onwards repeats.

**Comment by Kodiologist** [comment]
Good detective work. The tests for sequences aren't so good (they're redundant and verbose yet fail to check obvious things like `len`), and the documentation is vague on what operations are supposed to work.

**Comment by Kodiologist** [comment]
Likewise `(get (seq [n] (if (< n 10) n (end-sequence))) -1)` causes an infinite recursion, although `(get x -1)` works okay if `x` has already been fully populated by stepping through it with `for`.

**Comment by Jlobblet** [comment]
I'm currently working on a fix for this so I'll check that works too

**Comment by Kodiologist** [comment]
Although, the sort of thing that `Sequence` provides probably already exists elsewhere as a mature Python library. There's nothing very Hy-specific about it. If we find that, we can just drop `Sequence` and tell people to use that instead.

**Comment by Jlobblet** [comment]
> Although, the sort of thing that `Sequence` provides probably already exists elsewhere as a mature Python library. There's nothing very Hy-specific about it. If we find that, we can just drop `Sequence` and tell people to use that instead.

I suspect the typical Python approach would be to just define a custom generator function

**Comment by Kodiologist** [comment]
Other libraries that provide something sort of like this, none of which seem very mature:

- https://github.com/mitya57/infseq
- https://github.com/cjolowicz/lazysequence
- https://github.com/NCAR/seqgentools
- https://gitlab.com/Hares-Lab/cacheable-iterators
