### ISSUE TITLE
Documentation Missing

### ISSUE THREAD

**Issue by Jlobblet** [hylang/hyrule#64]
Something appears to have gone wrong with the most recent documentation build and https://hyrule.readthedocs.io/en/master/index.html is missing definitions for the contents of `anaphoric`, `argmove`, `collections`, and `control`.

**Comment by Kodiologist** [comment]
Thanks for reporting this. It should be fixed by https://github.com/hylang/sphinxcontrib-hydomain/commit/0428a54e2c233277036e401ef02ce35b0647d629.
